<?php


/**
 * This class defines the structure of the 'lecture_attendancy' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/27/16 15:29:38
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class LectureAttendancyTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.LectureAttendancyTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('lecture_attendancy');
		$this->setPhpName('LectureAttendancy');
		$this->setClassname('LectureAttendancy');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('LECTURE_ID', 'LectureId', 'INTEGER', 'lecture_schedule', 'ID', true, null, null);
		$this->addForeignKey('STUDENT_ID', 'StudentId', 'INTEGER', 'student', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('LectureSchedule', 'LectureSchedule', RelationMap::MANY_TO_ONE, array('lecture_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Student', 'Student', RelationMap::MANY_TO_ONE, array('student_id' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // LectureAttendancyTableMap
