<?php


/**
 * Skeleton subclass for representing a row from the 'lecture_attendancy' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/27/16 13:55:10
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LectureAttendancy extends BaseLectureAttendancy {

} // LectureAttendancy
