propel:
  user:
    id:       { type: integer, required: true, primaryKey: true, autoIncrement: true }
    login:    { type: varchar(255), required: true }
    password: { type: varchar(255), required: true }

  student:
    id:   { type: integer, required: true, primaryKey: true, autoIncrement: true }
    name: { type: varchar(255), required: true }

  book:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    name:         { type: varchar(255), required: true }

  teacher:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    name:         { type: varchar(255), required: true }

  study:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    name:         { type: varchar(255), required: true }

  library_record:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    name:         { type: varchar(255), required: true }
    book_id:      { type: integer, foreignTable: book, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }
    quantity:     { type: integer, required: true}

  lecture_schedule:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    teacher_id:   { type: integer, foreignTable: teacher, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }  
    study_id:     { type: integer, foreignTable: study, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }  

  library_user:
    id:                { type: integer, required: true, primaryKey: true, autoIncrement: true }
    student_id:        { type: integer, foreignTable: student, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }  
    library_record_id: { type: integer, foreignTable: library_record, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }  

  lecture_attendancy:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    lecture_id:   { type: integer, foreignTable: lecture_schedule, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }  
    student_id:   { type: integer, foreignTable: student, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }  

  graduation:
    id:           { type: integer, required: true, primaryKey: true, autoIncrement: true }
    grade:        { type: integer, required: true }    
    student_id:   { type: integer, foreignTable: student, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }
    study_id:     { type: integer, foreignTable: study, foreignReference: id, required: true, onDelete: cascade, onUpdate: cascade }    